const KEY='openradar:favorites:v1';
const categories=['全部','游戏开发','游戏AI与NPC','3D与动画','AI图片视频','Agent与MCP','Web与App','微信生态','教育产品','内容创作'];
const keywords={'游戏开发':['game','godot','phaser','pixi','roguelike','rpg'],'游戏AI与NPC':['npc','game ai','memory','behavior tree','agent'],'3D与动画':['3d','rigging','animation','motion','blender','mesh'],'AI图片视频':['image','video','diffusion','vision','text-to-image'],'Agent与MCP':['agent','mcp','codex','claude','workflow'],'Web与App':['typescript','react','next','web app','pwa'],'微信生态':['wechat','mini program','小程序','小游戏'],'教育产品':['education','learning','tutor','children'],'内容创作':['creator','content','audio','social media']};
const suggestions=['适合网页游戏的程序化地图生成器','允许商用的图片转3D与自动绑定骨骼','TypeScript NPC长期记忆系统','可本地运行的AI视频动作控制','适合Codex使用的MCP开发工具'];
const seed=[
{id:'github:ddfriday/repo-pulse',platform:'github',name:'repo-pulse',owner:'ddfriday',description:'追踪公开仓库快照，比较日、周、月增长并发现新兴 GitHub 项目。',url:'https://github.com/ddfriday/repo-pulse',stars:0,forks:0,language:'TypeScript',license:'MIT',createdAt:'2026-07-16',updatedAt:'2026-07-18',category:'Agent与MCP',score:87,topics:['trending','repository-discovery']},
{id:'github:ecosyste-ms/repos',platform:'github',name:'repos',owner:'ecosyste-ms',description:'跨代码托管平台的仓库元数据开放 API，是跨平台开源情报的重要底座。',url:'https://github.com/ecosyste-ms/repos',stars:0,forks:0,language:'Ruby',license:'AGPL-3.0',createdAt:'2022-01-01',updatedAt:'2026-07-20',category:'Web与App',score:94,topics:['open-source','metadata']},
{id:'github:X-lab2017/open-digger',platform:'github',name:'OpenDigger',owner:'X-lab2017',description:'开源生态活跃度、贡献者网络与 OpenRank 指标平台，可补充项目健康度分析。',url:'https://github.com/X-lab2017/open-digger',stars:0,forks:0,language:'TypeScript',license:'Apache-2.0',createdAt:'2021-01-01',updatedAt:'2026-07-20',category:'Agent与MCP',score:90,topics:['analytics','github']}
];
const state={projects:[...seed],results:[],favorites:load(),category:'全部',period:'today',install:null};
const $=id=>document.getElementById(id);const els=Object.fromEntries([...document.querySelectorAll('[id]')].map(x=>[x.id,x]));
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}function persist(){localStorage.setItem(KEY,JSON.stringify(state.favorites));counters()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function num(v=0){return new Intl.NumberFormat('zh-CN',{notation:v>=1000?'compact':'standard',maximumFractionDigits:1}).format(v)}
function days(p){return Math.max(1,(Date.now()-new Date(p.createdAt||Date.now()))/864e5)}function ago(v){if(!v)return'未知';const d=Math.max(0,Math.floor((Date.now()-new Date(v))/864e5));return d<1?'今天':d<30?`${d}天前`:d<365?`${Math.floor(d/30)}个月前`:`${Math.floor(d/365)}年前`}
function category(p){const text=[p.name,p.description,p.language,...(p.topics||[])].join(' ').toLowerCase();let best='Web与App',n=0;Object.entries(keywords).forEach(([k,a])=>{const s=a.filter(x=>text.includes(x)).length;if(s>n){best=k;n=s}});return best}
function score(p){if(p.score)return p.score;const pop=p.platform==='huggingface'?(p.likes||0)+Math.log10((p.downloads||0)+1)*25:(p.stars||0);const fresh=Math.max(0,25-Math.min(25,(Date.now()-new Date(p.updatedAt||0))/864e5));return Math.min(99,Math.round(Math.log10(pop+1)*22/Math.pow(days(p),.15)+fresh+(p.description?10:2)))}
function commercial(l=''){return/MIT|Apache|BSD|ISC|MPL|Unlicense/i.test(l)}function favorite(id){return state.favorites.find(x=>x.id===id)}function find(id){return state.projects.find(x=>x.id===id)||state.results.find(x=>x.id===id)||favorite(id)}
function toast(m){els.toast.textContent=m;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2200)}
function card(p,saved=false){const f=favorite(p.id),pop=p.platform==='huggingface'?(p.likes||0):(p.stars||0),second=p.platform==='huggingface'?(p.downloads||0):(p.forks||0),platform=p.platform==='huggingface'?'Hugging Face':'GitHub',av=p.avatar?`<img class="avatar" src="${esc(p.avatar)}" alt="">`:`<div class="avatar text">${esc(p.name.slice(0,2).toUpperCase())}</div>`,tags=saved&&f?.tags?.length?`<div class="saved-tags">${f.tags.map(t=>`<span class="saved-tag">${esc(t)}</span>`).join('')}</div>`:'',note=saved&&f?.note?`<div class="saved-note">${esc(f.note)}</div>`:'';return`<article class="card"><div class="card-top">${av}<div class="title"><h3 title="${esc(p.owner+'/'+p.name)}">${esc(p.name)}</h3><p>${esc(p.owner)} · 更新于${ago(p.updatedAt)}</p></div><button class="star ${f?'saved':''}" data-favorite="${esc(p.id)}">${f?'★':'☆'}</button></div><p class="desc">${esc(p.description||'暂无描述，需要进一步读取项目文档。')}</p><div class="badges"><span class="badge platform">${platform}</span><span class="badge">${esc(p.category||category(p))}</span>${p.language?`<span class="badge">${esc(p.language)}</span>`:''}<span class="badge ${commercial(p.license)?'good':'warn'}">${esc(p.license||'许可证待核查')}</span></div>${tags}${note}<div class="stats"><div class="stat"><b>${num(pop)}</b><span>${p.platform==='huggingface'?'Likes':'Stars'}</span></div><div class="stat"><b>${num(second)}</b><span>${p.platform==='huggingface'?'Downloads':'Forks'}</span></div><div class="stat"><b>${ago(p.createdAt)}</b><span>项目年龄</span></div><div class="score" style="--score:${score(p)}">${score(p)}</div></div><div class="actions"><a href="${esc(p.url)}" target="_blank" rel="noopener">打开项目</a><button data-analyze="${esc(p.id)}">适配分析</button>${saved?`<button data-remove="${esc(p.id)}">移出收藏</button>`:''}</div></article>`}
function bind(root){root.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>openDialog(b.dataset.favorite));root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.favorites=state.favorites.filter(x=>x.id!==b.dataset.remove);persist();toast('已移出收藏')});root.querySelectorAll('[data-analyze]').forEach(b=>b.onclick=()=>toast(`${find(b.dataset.analyze)?.name||'该项目'}：深度适配分析将在 Phase 0.2 接入`))}
function renderCategories(){els.categories.innerHTML=categories.map(c=>`<button class="category ${c===state.category?'active':''}" data-category="${c}">${c}</button>`).join('')}
function list(){let a=[...state.projects];if(state.category!=='全部')a=a.filter(p=>(p.category||category(p))===state.category);if(els.platform.value!=='all')a=a.filter(p=>p.platform===els.platform.value);if(els.license.value==='commercial')a=a.filter(p=>commercial(p.license));if(els.license.value==='unknown')a=a.filter(p=>!p.license||/待核查|unknown|other/i.test(p.license));const sort={today:(a,b)=>score(b)-score(a),week:(a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt),month:(a,b)=>(b.stars||b.likes||0)-(a.stars||a.likes||0),rising:(a,b)=>score(b)/Math.log10((b.stars||b.likes||0)+10)-score(a)/Math.log10((a.stars||a.likes||0)+10)};return a.sort(sort[state.period])}
function render(){const a=list();els.projectGrid.innerHTML=a.length?a.map(p=>card(p)).join(''):'<div class="empty"><h3>没有符合条件的项目</h3></div>';els.candidateMetric.textContent=state.projects.length;els.freshMetric.textContent=state.projects.filter(p=>days(p)<=30).length;bind(els.projectGrid)}
function renderFavorites(){const q=els.favoriteSearch.value.toLowerCase(),tag=els.tagFilter.value;let a=state.favorites.filter(f=>!q||[f.name,f.owner,f.note,...(f.tags||[])].join(' ').toLowerCase().includes(q)).filter(f=>tag==='all'||f.tags?.includes(tag));els.favoriteEmpty.hidden=!!a.length;els.favoriteGrid.innerHTML=a.map(p=>card(p,true)).join('');const tags=[...new Set(state.favorites.flatMap(f=>f.tags||[]))].sort(),cur=els.tagFilter.value;els.tagFilter.innerHTML='<option value="all">全部标签</option>'+tags.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');if(tags.includes(cur))els.tagFilter.value=cur;bind(els.favoriteGrid)}
function counters(){els.favoriteCount.textContent=state.favorites.length;els.savedMetric.textContent=state.favorites.length;renderFavorites();render();if(state.results.length)renderResults()}
function nav(view){document.querySelectorAll('.view,.nav').forEach(x=>x.classList.remove('active'));$(`${view}View`).classList.add('active');document.querySelector(`[data-view="${view}"]`).classList.add('active');els.sidebar.classList.remove('open');if(view==='favorites')renderFavorites()}
function openDialog(id){const p=find(id),f=favorite(id);if(!p)return;els.projectId.value=id;els.dialogTitle.textContent=f?`编辑收藏 · ${p.name}`:`收藏 · ${p.name}`;els.tags.value=f?.tags?.join(', ')||'';els.note.value=f?.note||'';els.action.value=f?.action||'later';els.dialog.showModal()}
async function radar(){els.status.textContent='正在查询免费 API…';els.status.className='';els.projectGrid.innerHTML='<div class="card skeleton"></div>'.repeat(6);const rs=await Promise.allSettled([githubRadar(),hfRadar()]),live=rs.filter(r=>r.status==='fulfilled').flatMap(r=>r.value);state.projects=live.length?dedupe([...live,...seed]):[...seed];els.status.textContent=live.length?`实时数据 · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`:'API暂不可用，显示种子数据';els.status.className=live.length?'live':'warn';render()}
async function githubRadar(){const d=new Date(Date.now()-30*864e5).toISOString().slice(0,10),u=`https://api.github.com/search/repositories?q=${encodeURIComponent(`created:>${d} stars:>20 archived:false`)}&sort=stars&order=desc&per_page=18`,r=await fetch(u,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw 0;return(await r.json()).items.map(github)}
function github(r){const p={id:`github:${r.full_name}`,platform:'github',name:r.name,owner:r.owner?.login||'',description:r.description||'',url:r.html_url,avatar:r.owner?.avatar_url||'',stars:r.stargazers_count||0,forks:r.forks_count||0,language:r.language||'',license:r.license?.spdx_id||'许可证待核查',updatedAt:r.pushed_at||r.updated_at,createdAt:r.created_at,topics:r.topics||[]};p.category=category(p);p.score=score(p);return p}
async function hfRadar(){const r=await fetch('https://huggingface.co/api/models?sort=trendingScore&direction=-1&limit=18&full=false');if(!r.ok)throw 0;return(await r.json()).map(hf)}
function hf(m){const [owner,...name]=m.id.split('/'),p={id:`huggingface:${m.id}`,platform:'huggingface',name:name.join('/')||m.id,owner,description:`${m.pipeline_tag?`任务：${m.pipeline_tag}。`:''}${(m.tags||[]).slice(0,4).join(' · ')}`,url:`https://huggingface.co/${m.id}`,likes:m.likes||0,downloads:m.downloads||0,language:m.library_name||m.pipeline_tag||'',license:(m.tags||[]).find(x=>x.startsWith('license:'))?.replace('license:','')||'许可证待核查',updatedAt:m.lastModified||m.last_modified||new Date().toISOString(),createdAt:m.createdAt||m.created_at||m.lastModified,topics:m.tags||[]};p.category=category(p);p.score=score(p);return p}
function dedupe(a){return[...new Map(a.map(p=>[p.id,p])).values()]}
async function search(q){const jobs=[];if(els.useGitHub.checked)jobs.push(fetch(`https://api.github.com/search/repositories?q=${encodeURIComponent(q+' archived:false')}&sort=stars&order=desc&per_page=20`,{headers:{Accept:'application/vnd.github+json'}}).then(r=>{if(!r.ok)throw 0;return r.json()}).then(x=>x.items.map(github)));if(els.useHF.checked)jobs.push(fetch(`https://huggingface.co/api/models?search=${encodeURIComponent(q)}&sort=downloads&direction=-1&limit=20&full=false`).then(r=>{if(!r.ok)throw 0;return r.json()}).then(x=>x.map(hf)));if(!jobs.length)return toast('请至少选择一个数据源');els.searchSummary.textContent='正在跨平台搜索…';els.searchGrid.innerHTML='<div class="card skeleton"></div>'.repeat(4);const rs=await Promise.allSettled(jobs);state.results=dedupe(rs.filter(r=>r.status==='fulfilled').flatMap(r=>r.value));sortResults();els.searchSummary.textContent=`“${q}” 找到 ${state.results.length} 个候选。许可证需在正式采用前再次核查。`;renderResults()}
function sortResults(){const s={score:(a,b)=>score(b)-score(a),popular:(a,b)=>(b.stars||b.likes||0)-(a.stars||a.likes||0),fresh:(a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)};state.results.sort(s[els.sort.value])}function renderResults(){els.searchGrid.innerHTML=state.results.length?state.results.map(p=>card(p)).join(''):'<div class="empty"><h3>没有找到结果</h3><p>尝试使用英文技术关键词。</p></div>';bind(els.searchGrid)}
function init(){renderCategories();els.suggestions.innerHTML=suggestions.map(q=>`<button class="chip" data-query="${esc(q)}">${esc(q)}</button>`).join('');document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.view));els.categories.onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;state.category=b.dataset.category;renderCategories();render();nav('radar')};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.period=b.dataset.period;render()});els.platform.onchange=render;els.license.onchange=render;els.refresh.onclick=radar;els.menu.onclick=()=>els.sidebar.classList.toggle('open');els.quickSearch.onkeydown=e=>{if(e.key==='Enter'&&e.target.value.trim()){els.query.value=e.target.value.trim();nav('search');search(els.query.value)}};els.searchForm.onsubmit=e=>{e.preventDefault();const q=els.query.value.trim();q?search(q):toast('请输入搜索需求')};els.sort.onchange=()=>{sortResults();renderResults()};els.suggestions.onclick=e=>{const b=e.target.closest('[data-query]');if(b){els.query.value=b.dataset.query;search(b.dataset.query)}};els.favoriteForm.onsubmit=e=>{e.preventDefault();const p=find(els.projectId.value);if(!p)return;const item={...p,tags:els.tags.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),note:els.note.value.trim(),action:els.action.value,savedAt:favorite(p.id)?.savedAt||new Date().toISOString()};state.favorites=[item,...state.favorites.filter(x=>x.id!==p.id)];persist();els.dialog.close();toast('已保存到收藏库')};els.closeDialog.onclick=els.cancel.onclick=()=>els.dialog.close();els.favoriteSearch.oninput=renderFavorites;els.tagFilter.onchange=renderFavorites;els.export.onclick=()=>{const blob=new Blob([JSON.stringify(state.favorites,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`openradar-favorites-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)};els.clear.onclick=()=>{if(state.favorites.length&&confirm('确定清空全部收藏吗？')){state.favorites=[];persist();toast('收藏已清空')}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.install=e;els.install.hidden=false});els.install.onclick=async()=>{if(state.install){state.install.prompt();await state.install.userChoice;state.install=null;els.install.hidden=true}};counters();radar();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}init();
